project:
  type: website
  output-dir: docs

website:
  title: "BWPR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: week1.qmd
        text: Week 1
      - href: week2.qmd
        text: Week 2
      - href: week3.qmd
        text: Week 3
      - href: week4.qmd
        text: Week 4
      - href: week5.qmd
        text: Week 5
      - href: week6.qmd
        text: Week 6
      - href: week7.qmd
        text: Week 7
      - href: dsow.qmd
        text: DSOW
      - href: tracker.qmd
        text: Tracker
    title: false
    background: "#000000"
    foreground: "#E6E6DD"
    collapse-below: lg
    logo: img/logo.png

format:
  html:
    theme: zephyr
    css: styles.css?v=1.0
    toc: true
    includes:
      in-header: styles.css?v=1.0
    page-layout: full



