---
title: "Rankings Tracker"
---

<html>
<head>
  <style>
    #vis.vega-embed {
      width: 100%;
      display: flex;
    }

    #vis.vega-embed details,
    #vis.vega-embed details summary {
      position: relative;
    }
  </style>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega-lite@5.15.1"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>
<body>
  <div id="vis"></div>
  <script>
    (function(vegaEmbed) {
      var spec = {"config": {"view": {"continuousWidth": 300, "continuousHeight": 300}, "legend": {"disable": true}}, "layer": [{"data": {"name": "data-7c743e1b1781fe6139095710340d1edb"}, "mark": {"type": "line", "point": true}, "encoding": {"color": {"field": "Team", "type": "nominal"}, "tooltip": [{"field": "Team", "type": "nominal"}, {"field": "Week", "type": "quantitative"}, {"field": "Ranking", "type": "quantitative"}, {"field": "Ranking_Change_Formatted", "type": "nominal"}], "x": {"axis": {"labelAngle": 90}, "field": "Week", "title": "Week", "type": "ordinal"}, "y": {"field": "Ranking", "scale": {"domain": [1, 10], "reverse": true}, "title": "Ranking", "type": "quantitative"}}}, {"data": {"name": "data-4aeb04e39cb71d03f0ff6eb29979f709"}, "mark": {"type": "text", "align": "left", "dx": 5, "dy": -5}, "encoding": {"color": {"field": "Team", "type": "nominal"}, "text": {"field": "Team", "type": "nominal"}, "x": {"field": "Week", "type": "ordinal"}, "y": {"field": "Ranking", "type": "quantitative"}}}], "height": 400, "title": "Power Rankings Tracker", "width": 600, "$schema": "https://vega.github.io/schema/vega-lite/v5.15.1.json", "datasets": {"data-7c743e1b1781fe6139095710340d1edb": [{"Team": "Two Curls One Kupp", "Week": 1, "Ranking": 1, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Ladies Love Cool Jalen", "Week": 1, "Ranking": 2, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Njigbas in Paris", "Week": 1, "Ranking": 3, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Ass Etienne Szn", "Week": 1, "Ranking": 4, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Rico's Rizzlers", "Week": 1, "Ranking": 5, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Team10Chrysler", "Week": 1, "Ranking": 6, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Big Dak Energy", "Week": 1, "Ranking": 7, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Butker's Housewife Brigade", "Week": 1, "Ranking": 8, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Mike Vick's Underdogs", "Week": 1, "Ranking": 9, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "The Dicker McDickersons", "Week": 1, "Ranking": 10, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Two Curls One Kupp", "Week": 2, "Ranking": 1, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Rico's Rizzlers", "Week": 2, "Ranking": 2, "Ranking_Change": -3, "Ranking_Change_Reversed": 3, "Ranking_Change_Formatted": "+3"}, {"Team": "Ass Etienne Szn", "Week": 2, "Ranking": 3, "Ranking_Change": -1, "Ranking_Change_Reversed": 1, "Ranking_Change_Formatted": "+1"}, {"Team": "Njigbas in Paris", "Week": 2, "Ranking": 4, "Ranking_Change": 1, "Ranking_Change_Reversed": -1, "Ranking_Change_Formatted": "-1"}, {"Team": "Team10Chrysler", "Week": 2, "Ranking": 5, "Ranking_Change": -1, "Ranking_Change_Reversed": 1, "Ranking_Change_Formatted": "+1"}, {"Team": "Ladies Love Cool Jalen", "Week": 2, "Ranking": 6, "Ranking_Change": 4, "Ranking_Change_Reversed": -4, "Ranking_Change_Formatted": "-4"}, {"Team": "Big Dak Energy", "Week": 2, "Ranking": 7, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Butker's Housewife Brigade", "Week": 2, "Ranking": 8, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Mike Vick's Underdogs", "Week": 2, "Ranking": 9, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "The Dicker McDickersons", "Week": 2, "Ranking": 10, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}], "data-4aeb04e39cb71d03f0ff6eb29979f709": [{"Team": "Two Curls One Kupp", "Week": 2, "Ranking": 1, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Rico's Rizzlers", "Week": 2, "Ranking": 2, "Ranking_Change": -3, "Ranking_Change_Reversed": 3, "Ranking_Change_Formatted": "+3"}, {"Team": "Ass Etienne Szn", "Week": 2, "Ranking": 3, "Ranking_Change": -1, "Ranking_Change_Reversed": 1, "Ranking_Change_Formatted": "+1"}, {"Team": "Njigbas in Paris", "Week": 2, "Ranking": 4, "Ranking_Change": 1, "Ranking_Change_Reversed": -1, "Ranking_Change_Formatted": "-1"}, {"Team": "Team10Chrysler", "Week": 2, "Ranking": 5, "Ranking_Change": -1, "Ranking_Change_Reversed": 1, "Ranking_Change_Formatted": "+1"}, {"Team": "Ladies Love Cool Jalen", "Week": 2, "Ranking": 6, "Ranking_Change": 4, "Ranking_Change_Reversed": -4, "Ranking_Change_Formatted": "-4"}, {"Team": "Big Dak Energy", "Week": 2, "Ranking": 7, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Butker's Housewife Brigade", "Week": 2, "Ranking": 8, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "Mike Vick's Underdogs", "Week": 2, "Ranking": 9, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}, {"Team": "The Dicker McDickersons", "Week": 2, "Ranking": 10, "Ranking_Change": 0, "Ranking_Change_Reversed": 0, "Ranking_Change_Formatted": "0"}]}};
      var embedOpt = {"mode": "vega-lite"};

      function showError(el, error){
          el.innerHTML = ('<div style="color:red;">'
                          + '<p>JavaScript Error: ' + error.message + '</p>'
                          + "<p>This usually means there's a typo in your chart specification. "
                          + "See the javascript console for the full traceback.</p>"
                          + '</div>');
          throw error;
      }
      const el = document.getElementById('vis');
      vegaEmbed("#vis", spec, embedOpt)
        .catch(error => showError(el, error));
    })(vegaEmbed);

  </script>
</body>
</html>