---
title: "Week 6"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Butker's Housewife Brigade** &nbsp;&nbsp; **-**
    <br> Still number one. Let's see if the newly acquired players contribute to this squad's success this week.
    
2. **Team10Chrysler - GET A NAME** &nbsp;&nbsp; **+5**
    <br> This is mostly about finally showing some respect to this 4-1 team so they take me off their whiteboard and come back to earth. Also their lineup is finally healthy and they look a lot better than last week. Also congrats on winning the battle of the brothers.
    
3. **Njigbas in Paris** &nbsp;&nbsp; **+1**
    <br> A scrappy win with a few key pieces out injured. Let's see if they can keep holdin' it down without Malik and JT.

4. **Ass Etienne Szn** &nbsp;&nbsp; **-2**
    <br> Yes, Joe Sheisty and Ja'Marr are back, but Nico is gone for a few weeks and the RBs are junk. Can they stay perfect?

5. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-2**
    <br> No movement for this squad this week. Not a lot changed here and we didn't see a particularly impressive or worrying performance so this team holds their position.

6. **Raheem's Rizzlers** &nbsp;&nbsp; **-**
    <br> Josh has chilled out the past few weeks, will that continue or will he get back to his high-scoring ways? The WR situation is rough, sort of an opposite critique of Ass Etienne Szn.

7. **Two Curls One Kupp** &nbsp;&nbsp; **+1**
    <br> As the Curls begin to bounce back from some of the injuries they faced, I have to say, I figured this team would be worse off than 2-3.

8. **Mike Vick's Underdogs** &nbsp;&nbsp; **-3**
    <br> The 'dogs have been underperforming all year and it's time it shows up in the rankings. Show me a win and maybe they'll bounce back a bit in the next few weeks.

9. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br> Starting lineup: Junk, Junk, Junk, Ceedee, Tee Higgins, Junk, Junk, Junk, Junk, Junk

10. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> I don't have much to say about this team. Pray for Mixon to come back and help out.