---
title: "Week 5"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Butker's Housewife Brigade** &nbsp;&nbsp; **+1**
    <br> Up until a couple hours ago, this team was slotted in at number 2. Then, they comitted highway robbery and picked up a first round pick WR and a second round pick RB. This roster will be pretty stacked going forward.
    
2. **Ass Etienne Szn** &nbsp;&nbsp; **+1**
    <br> We gotta put some respect on a 4-0 start. The RB situation is still looking rough but Chase and Collins keep stepping up to carry the load. Kelce finally woke up and we hope he keeps improving now with the extra targets available due to Rashee Rice's injury.
    
3. **Ladies Love Cool Jalen** &nbsp;&nbsp; **+1**
    <br> Jayden Daniels to the moon! The Commies' QB is the new starting QB for this squad and he looks like he's trying to stay at the top of the depth chart. Kyren Williams and DK Metcalf have also been surpassing expectations this season, while Brian Robinson and Diontae Johnson provide more unexpected value.

4. **Njigbas in paris** &nbsp;&nbsp; **-3**
    <br> 4 injuries to starters last week drop this squad 3 spots. Rashee is gone for the year, Nabers is in concussion protocol and looks like he'll miss at least a week, JT has another high-ankle sprain and will likely miss time, and George Kittle is hurt for the second time this season. The bright side is that 3/4 of these injuries shouldn't last too long. If they do, this team will drop further.

5. **Mike Vick's Underdogs** &nbsp;&nbsp; **-**
    <br> No movement for this squad this week. Not a lot changed here and we didn't see a particularly impressive or worrying performance so this team holds their position.

6. **Raheem's Rizzlers** &nbsp;&nbsp; **-**
    <br> King Henry is so back baby! Unfortunately, other than Josh, Derrick, and Alvin, the cupboards are bare here. We need to see a bounce back game from Tyreek or someone else to start contributing before we bump them up the rankings.

7. **Team10Chrysler - GET A NAME** &nbsp;&nbsp; **-**
    <br> A down week from K1 and James Cook is no reason to panic. We saw Jayden Reed rebound with Jordan Love back under center, and the lineup is about to get a huge boost with AJ Brown, Trey McBride, and Jonathan Brooks set to get back to action.

8. **Two Curls One Kupp** &nbsp;&nbsp; **+2**
    <br> Scrappy. This team isn't going away quietly. A monster return from injury from Ken Walker and a strong performance from each of the team's WRs. Jordan Love appears to be a great replacement for Richardson and Chase Brown may even be lineup worthy.

9. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br> Congrats on putting one up in the W column! Hopefully a change of scenery for Davante Adams when he gets back from his hamstring spark some production. 

10. **Big Dak Energy** &nbsp;&nbsp; **-2**
    <br> An 0-4 start leading to a panic trade to try and change the vibes lead to a drop to the bottom of BWPR. The star power is gone and with it, the ability to hit a home run. With the team's weekly ceiling significantly lowered, the likelihood of pulling off an upset shrinks.