---
title: "Week 1"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Two Curls One Kupp** 
    <br>Prioritized RB and WR balance with stars at both positions, got good value at QB and TE, and managed to pick up the handcuff to his injury-prone RB1. Great start to the season! 
    <br><br>Question for the season: Will star players stay healthy? 

2. **Ladies Love Cool Jalen**
    <br>Good balance at RB and WR with two elite RBs to rely on. WRs are all the WR1 on their teams and should see heavy volume. Prioritized QB and left TE until the later rounds relying on the depth at the position. Exciting draft!
    <br><br>Question for the season: Will leaving TE until late in the draft create a competitive disadvantage at the position?

3. **Njigbas in Paris**
    <br>Similar roster construction to #2, but prioritized a high-level TE over an Elite QB. An exciting WR corps and 2 Elite RBs will keep this manager from being bored watching his team this year. The lack of the QB's rushing ability, and a lack of RB depth puts this team at #3. Finally, adding Hockenson in the 13th to create an extra roster space was a nifty move that didn't go unnoticed.
    <br><br>Question for the season: Will second year Rashee Rice and rookie Malik Nabers break out to become stars?

4. **Ass Etienne Szn**
    <br>First of all, outstanding team name! A great WR group and the almost-GOAT TE set up a reliable foundation for this squad. The lack of depth at RB and the QBs inability to score points on the ground are what may limit this team. However, we do like the Sheisty-Chase stack!
    <br><br>Question for the season: Will Stevenson or Moss surpass expectations and add some juice to the RB group?

5. **Rico's Rizzlers**
    <br>An Elite WR, QB, and TE will carry this team to a safe floor each week. The lack of depth at the WR position combined with a WR1 who tends to miss time each year means for this team to explode they'll need some historically below-average WRs to take a big stride this year. There's no denying the depth of TE on this team, will this unusual lineup construction translate to success? Let's wait and see!
    <br><br>Question for the season: Can Josh Allen stay the best player in fantasy without a single starting-quality WR to throw to? 

6. ***Team10Chrysler - GET A NAME***
    <br>This team boats one of the best WR groups in the league but lacks star power at RB. A pairing of an up-and-coming TE and a perenially-undervalued QB give this manager a stack we should all watch out for. 
    <br><br>Question for the season: Will the Cardinals offense take a big step this year and return on this manager's heavy investment in them?

7. **Big Dak Energy**
    <br>This was the hardest team to rank. Their season may be the most uncertain. With maybe the highest-variance player in all of fantasy in De'Von Achane, and an RB that is severely volume dependent in Rachaad White, along with two WRs (Deebo Samuel and Stefon Diggs) whos consistent volume is hard to predict, makes it very hard to judge this team. To top it off, Dak Prescott fills the QB spot with another player who could finish the season anywhere from MVP to unsigned over the offseason. Ironically, this team also features maybe the safest first round pick of the draft in Amon-Ra St.Brown.
    <br><br>Question of the season: Can Dak and Rachaad repeat their top-5 performances at their positions from last season?

8. **Butker's Housewife Brigade**
    <br>Hope the volcano was worth drafting Butker and 3 QBs. Bijan and a young WR tandem make up most of the total possible upside of this team. If they excell, we'll see this team rising up these rankings in the coming weeks. If not, I'm not sure there are many other pieces of this team that can propel them up the ranks.
    <br><br>Question of the season: Can Lamar repeat as MVP and give this team a consistent superstar to lean on?

9. ***CantGuardBandaidMike - GET A NAME***
    <br>This team has some question marks. First, can Justin Jefferson prove that he can make any QB into Kirk Cousins? Second, can Drake London, Zay Flowers, and Terry McLaurin take the leap we've been for from each of them? They're all in an exciting environment with serious additions to their offenses, but will they be worth the hype? Finally, a lack of RB depth and the worst TE in the league may mean this team needs to be carried to success by their star QB.
    <br><br>Question for this season: Can Saquon pull off the career revival and get back to his explosive, fantasy-breaking self behind a solid Eagles' O-line?

10. **The Dicker McDickersons**
    <br>Welcome to your first season of Barns' Weekly Power Rankings! With the league's worst RB group and having reached on a second-year pocket QB, this team will lean on their deep WR room and two solid TEs to drag them up the rankings as the season develops.
    <br><br>Question for the season: Will this manager find RB help on the waiver wire or through the trade market?

<br><br>
<h2 class="subtitle">Draft Awards</h2>

**Most Hated Selection**
<br>Player: Zay Flowers
<br>Drafted by: CantGuardBandaidMike
<br>Votes: 5 Poops and 1 Thumbs Down
<br>Pick: Rd 5 Pick 8

**Most Loved Selection**
<br>Player: Isaiah Pacheco
<br>Drafted by: Two Curls One Kupp
<br>Votes: 3 Graduates
<br>Pick: Rd 2 Pick 9

**Most Poop Votes**
<br>Winner: CantGuardBandaidMike - 14
<br>Runner-up: Big Dak Energy - 7 *5 Poops were mistakenly assigned to Ass Etienne Szn