---
title: "Week 10"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Butker's Housewife Brigade** &nbsp;&nbsp; **-**
    <br> This is still the best roster in the league. At only one win above .500 they're producing some very dissapointing results, but they still have the highest ceiling.
    
2. **Ass Etienne Szn** &nbsp;&nbsp; **+3**
    <br> 'tis the Szn. This teams vibes are unmatched. They're chillin' playing Madden in the locker room, excited to get on the bus to the next game, they're just having a grand ol' time.
    
3. **Big Ass Boy** &nbsp;&nbsp; **-1**
    <br> Love the new name. When this team is healthy they have a nasty roster, especially with Ladd and Garrett performing.

4. **Mike Vick's Underdogs** &nbsp;&nbsp; **+3**
    <br> 4 Ws in a row is legit. Do the dogs have their bite back? Either way koodos are in order as they bounced back from a 1-4 start to wind up smack dab in the middle of the playoff race.

5. **Njigbas in Paris** &nbsp;&nbsp; **-2**
    <br> I know I'm about to hear about this one but this roster is sort of pieced together at this point from all the injuries. I don't expect JSN to put up 37 every week.

6. **Raheem's Rizzlers** &nbsp;&nbsp; **-**
    <br> The Rizzlers just keep chugging along. They're not flashy but they're more or less consistent.

7. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-3**
    <br> This ship has a ton of holes. They're putting up lots of points but don't win games. The story of the season has been Breece and DJ dissapointing us over and over again. 3 Ls in a row has dropped LL Cool Jalen straight out of the playoff picture.

8. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br> This squad is on a sneaky rise to try and chase a playoff berth but they still haven't been putting up the same amount of points on a weekly basis as the teams ahead of them. 

9. **Two Curls One Kupp** &nbsp;&nbsp; **-**
    <br> They need their stars back from IR asap.

10. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> Just 3 Ws out of a playoff spot but it still feels like the Ws they have put up had a lot to do with luck.