---
title: "Week 7"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Butker's Housewife Brigade** &nbsp;&nbsp; **-**
    <br> Another week at the top for the Brigade as they come within one win of first place.
    
2. **Njigbas in Paris** &nbsp;&nbsp; **+1**
    <br> The return of Nabers gives this squad the juice they need to get back up to number 2.
    
3. **Team10Chrysler - GET A NAME** &nbsp;&nbsp; **-1**
    <br> Is James Cook okay? Will Davante eat into Garrett Wilson's huge workload? They drop one spot while we find out the answers to this question.

4. **Ladies Love Cool Jalen** &nbsp;&nbsp; **+1**
    <br> Even with this team's namesake getting his favourite weapons back, the rookie refuses to give him his starting spot back as he keeps them in the W column.

5. **Ass Etienne Szn** &nbsp;&nbsp; **-1**
    <br> You hate to see an undefeated season come to an end, but it feels like this L was well past due.

6. **Raheem's Rizzlers** &nbsp;&nbsp; **-**
    <br> All hail King Henry. Pray that Tyreek starts doing Tyreek things again soon because this team needs a spark.

7. **Two Curls One Kupp** &nbsp;&nbsp; **-**
    <br> This team is showing some heart without their stars.

8. **Mike Vick's Underdogs** &nbsp;&nbsp; **-**
    <br> The dogs are all bark and no bite. They're putting up some points but can't seem to close the deal.

9. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br> No movement this week, but win your matchup and I have a feeling you'll find yourself in the 8 spot next week.

10. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> 0-6... 'Nuff said.
