---
title: "Week 2"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Two Curls One Kupp** &nbsp;&nbsp; **-**
    <br>This team looks strong. Our number one team from last week had a strong opening week, putting up the highest score across the league with Christian McCaffrey sitting on the bench. The likely return of CMC for week 2 means we like Two Curls One Kupp's chances of starting 2-0.
    
2. **Rico's Rizzlers** &nbsp;&nbsp; **+3**
    <br>We found our answer to the question "Will Josh Allen be able to maintain his fantasy dominance with no standout WRs"... Yes, yes he will. The only question now is who is going to start at WR alongside Tyreek next week?
    
3. **Ass Etienne Szn** &nbsp;&nbsp; **+1**
    <br>This team's namesake's backfield appears to be more split than we foresaw. By hoping that Tank Bigsby's heavy involvement in week 1 doesn't continue and that the Bengals get their swag back sooner rather than later, and by assuming that Chase and Smith will be back in the lineup for week 2, we foresee this team getting stronger this week.

4. **Njigbas in Paris** &nbsp;&nbsp; **-1**
    <br>A good showing in week 1 for this squad, but at the cost of their starting QB. With Jordan Love week-to-week, and no backup on the roster, the uncertainty at QB in week 2 drops this team a notch in the power rankings for this week.

5. ***Team10Chrysler - GET A NAME*** &nbsp;&nbsp; **+1**
    <br>Losing Puka Nacua (we like saying his full name) to the IR is a tough hit to this squad, but on the other hand, Jayden Reed looks like the steal of the draft and the James' heavy usage in week 1 are promising signs of their roles in their offenses. The main question is will Jayden Reed be able to keep it up without Jordan Love at QB? Get a name.

6. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-4**
    <br>A dissapointing week 1 performance by this crew of WRs leaves a lot to be desired going forward. A couple unfavourable matchups and an injured TE lay ahead in week 2 cause a major slide in the rankings for this team.

7. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br>This team faces a very similar situation to the team above, a lack of explosivity from it's stars in week 1 and an injured TE means this team better turn it around in week 2.

8. **Butker's Housewife Brigade** &nbsp;&nbsp; **-**
    <br>This team's top 3 WRs are MHJ, Chris Olave, and Amari Cooper. Together they put up 8 pts last week. If they don't turn things around in a major way next week I have a feeling we'll see this squad right back here for week 3.

9. **Mike Vick's Underdogs** &nbsp;&nbsp; **-**
    <br>Saquon is the only one of the Underdogs to be pulling his weight. If nobody else starts pitching in, these dogs are gonna stay underdogs.

10. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br>This team's 2 star WRs didn't do enough to carry this team to a win in week 1. Unless they put up 35 each going forward, they're going to need more from other contributors. The apparent irrelavance of Mark Andrews is another panic signal for this manager.


