---
title: "Week 4"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Njigbas in Paris** &nbsp;&nbsp; **+1**
    <br> Yes, I know I'm about to hear you all screaming and hollering that "this team lost last week so why are they rising in the rankings?" Because Malik Nabers is a monster, Rashee Rice is a monster, the two starting RBs are more than dependable, and Mike Evans and Brandon Aiyuk are both bound to start producing sooner rather than later.
    
2. **Butker's Housewife Brigade** &nbsp;&nbsp; **+2**
    <br> Do I expect this team to put 180 pts every week? No, but Chris Olave and Amari Cooper showing signs of life is a good sign! It's also promising to see Chris Godwin stay consistent as it is to see Monty keep getting this kind of volume. Hopefully Mixon will be back soon.
    
3. **Ass Etienne Szn** &nbsp;&nbsp; **-2**
    <br> I hate to drop a team that won their matchup to stay undefeated but with the way Etienne is playing, this team is highly reliant (maybe too reliant) on the success of the Bengal's offence. It was important to see Burrow and Chase finally play at the level we're used to -- for God's sake, hopefully Kelce can follow suit this week! Devonta Smith getting concussed doesn't help.

4. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-1**
    <br> Two of the top 5 RBs in fantasy lead the the way for this squad. Two elite QB options, provide a safe floor at the position and the WR room provides safe production. TE is a problem here for sure, but we don't expect to see a 0 from the kicker every week.

5. **Mike Vick's Underdogs** &nbsp;&nbsp; **+1**
    <br> I think we just saw this team's ceiling. Saquon is an animal and he'll need to keep being one to keep carrying this squad on his back. Dallas Goedert was a great start (check the DSOW) and he is likely in line for some more volume if Devonta and AJ Brown miss next week, but we can't expect production like this from him every week. Further, Zach Charbonnet was a nice pickup for a couple weeks but with Ken Walker expected back soon, we can't expect him to stay startable.

6. **Raheem's Rizzlerss** &nbsp;&nbsp; **+1**
    <br> Yes, Lebron is right, it's very fun to watch Josh Allen play football -- and maybe even moreso to watch him play fantasy football. It's also fun to watch King Henry play like he did 2 years ago, so we moved this team up one because he showed us he can still pull a performance like that out of his hat now and then. However, I don't expect him to see volume or efficiency like that every week. The reason this team doesn't move up higher is that the WR position is still an issue. Tyreek was drafted to be the WR1 overall and now it's questionable if he's even reliable WR1 for his team. You have lots of RBs and Mike Vick's Underdogs have lots of WRs... I can smell a trade that might bump you both up the rankings.

7. **Team10Chrysler - GET A NAME** &nbsp;&nbsp; **-2**
    <br> I know, I know, they're 3-0, but they just beat our last ranked team and lost their star TE to a concussion in the process. With AJ Brown and Trey McBride out and Garrett Wilson not producing like a 2nd round pick should be, this team isn't as threatening as they could be with everyone in the lineup.

8. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> 0-3 is a tough spot to be. It's nice to see Dak put up a big day, but equally dissapointing to see the 'boys defense drop a deuce on the field like that. Will we see Achane keep putting up the numbers he did in week 1 and 2 or will opposing defenses focus on taking him out of the game with Skylar Thompson under center?

9. **The Dicker McDickersons** &nbsp;&nbsp; **-**
    <br> Week 3 was this team's best chance at a win so far, with their opponent putting up only 110, but they weren't able to scrape together enough production from their star WRs. Hopefully we see CeeDee and Dak get back on the rhythm se wee from them last year as this team will never get near their ceiling without CeeDee and Davante carrying the load.

10. **Two Curls One Kupp** &nbsp;&nbsp; **-**
    <br> I'm not certain but I think 79 pts is probably near the lowest we've seen a team put up in this league. Things are looking bleak here. Hopefully Ken Walker can come back to help this team out but even then, they won't be too scary until their big names come back from injury and their Colts' stack come to life.