---
title: "Week 9"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Butker's Housewife Brigade** &nbsp;&nbsp; **-**
    <br> The Brigade still have the top spot even though they can't seem to get ahead of those pesky Ass Etienne Szn boys.
    
2. **Team10Chrysler - GET A NAME** &nbsp;&nbsp; **+1**
    <br> The no-namers (can't believe you still don't have a name and it's week 9... embarassing) are back to full strength with AJ and Puka back and they look good!
    
3. **Njigbas in Paris** &nbsp;&nbsp; **-1**
    <br> I think this team should really be #4 and LL Cool Jalen should 3 but since they just won that head to head last week we give 'em the respect of the higher ranking.

4. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-**
    <br> Jalen got his cool back last week and we certainly loved it. We continue to wait for the Jets to give Breece hall on the goal line and let him show his first round value.

5. **Ass Etienne Szn** &nbsp;&nbsp; **-**
    <br> Yes, you're in first and you're 6-2 but we don't know how. It just keeps coming up AES for whatever reason. 

6. **Raheem's Rizzlers** &nbsp;&nbsp; **-**
    <br> Tua came back and Tyreek didn't look much better... we'll give them another week to right the ship before we overreact.

7. **Mike Vick's Underdogs** &nbsp;&nbsp; **+1**
    <br> The dogs are hard to figure out, but I do know that starting the Raiders' DEF "is a bold strategy cotton, let's see how it plays out for 'em".

8. **The Dicker McDickersons** &nbsp;&nbsp; **+1**
    <br> The McDickersons see their highest ranking of the season this week on the heels of an explosion from CeeDee and Josh Jacobs.

9. **Two Curls One Kupp** &nbsp;&nbsp; **-2**
    <br> The Curls get their namesake back but he didn't show us the same explosion we expect from him. We'll see if he warms back up... 'cuz this squad sure needs it.

10. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> BDE finally notched one up in the W column! A round of applause please everyone! Unfortunately, we need to see more from this crew.