---
title: "Week 11"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Ass Etienne Szn** &nbsp;&nbsp; **+1**
    <br> Not only are they etienne but they absolutely cooking! With Collins back, this squad looks strong.
    
2. **Butker's Housewife Brigade** &nbsp;&nbsp; **-1**
    <br> Roster is good but not catching up to the Eaters. They gotta start performing like they can.
    
3. **Big Ass Boy** &nbsp;&nbsp; **-**
    <br> This roster looks good with Puka back.

4. **Mike Vick's Underdogs** &nbsp;&nbsp; **-**
    <br> The middle of the table here is tight but we like this team the best of the next 3.

5. **Raheem's Rizzlers** &nbsp;&nbsp; **+1**
    <br> They finally rise up out of the 6 spot!

6. **Njigbas in Paris** &nbsp;&nbsp; **-1**
    <br> Gibbs is great but the rest of the roster isn't shining off the page.

7. **Two Curls One Kupp** &nbsp;&nbsp; **+2**
    <br> The stars are starting to heal up and the team is looking much better than a couple weeks ago!

8. **Ladies Love Cool Jalen** &nbsp;&nbsp; **-1**
    <br> This team is so unbearingly frustrating to watch every week. The Jets of Shiva.

9. **The Dicker McDickersons** &nbsp;&nbsp; **-1**
    <br> Just don't love the potential as much of the two above them. With Dak out CeeDee's explosivity is compromised.

10. **Big Dak Energy** &nbsp;&nbsp; **-**
    <br> In the torture chamber.