---
title: "Week 3"
---

<h2 class="subtitle">Power Rankings</h2>

1. **Ass Etienne Szn** &nbsp;&nbsp; **+2**
    <br> This team is 2-0 and have frankly not been operating anywhere near 100%. If the bengals stack, Taylor Swift's boyfriend, and the team's namesake get their act together this team will be hard to beat.
    
2. **Njigbas in Paris** &nbsp;&nbsp; **+2**
    <br> The deepest WR room in the league just got a little boost as we expect Brandon Aiyuk to break out of his slump with Deebo out for a couple weeks. If the Lions get their offense moving again this team will be even scarier.
    
3. **Ladies Love Cool Jalen** &nbsp;&nbsp; **+3**
    <br> The depth of this team is driving its success. Dobbins and Robinson are way outpacing expectations and providing great value from late in the draft. The main question here is will the injuries to the Rams' WRs help or harm Kyren's fantasy production?

4. **Butker's Housewife Brigade** &nbsp;&nbsp; **+4**
    <br> This week we saw many of the questions we had about this team last week laid to rest -- MHJ and Brock Bowers looks like the real deal. If Joe Mixon's ankle turns out not to be a big deal we'll likely see this team rise another ranking next week. For now, the lack of depth at RB poses a risk.

5. ***Team10Chrysler - GET A NAME*** &nbsp;&nbsp; **-**
    <br> We'd like to put the first place team higher in these rankings but with AJ Brown out for a couple weeks and Jayden Reed appearing not to be a factor without Jordan Love, this team will need Kyler and the James's to keep carrying them. Hopefully we see the Jets lean on the throttle a little and start putting up some points... if we do, Wilson may begin contributing like the second round pick he is.

6. **Mike Vick's Underdogs** &nbsp;&nbsp; **+3**
    <br> Saquon is that dude. Jjettas is proving to us once again that he's QB proof -- he's out here catching 97 yd TDs from Kirk Cousins' cousin. Drake London showed us that he's not incompetent. If Ken Walker's injury persists, Charbonnet will continue to be a great flex start.

7. **Raheem's Rizzlers** &nbsp;&nbsp; **5**
    <br> This team drops in the ranking largely due to the concern around Tyreek Hill. It's difficult to value him the same way without Tua there to force feed him targets each week. This team's 2 TE strategy also has yet to pay off and is looking questionable with the lack of volume either of the TEs have been getting so far. We can give thanks here to Alvin doing his best impression of his 2020 self.

8. **Big Dak Energy** &nbsp;&nbsp; **-1**
    <br> We don't have much to say about this team this week. Achane looks great and the sun god showed us some sign of life this week which is a positive going forward. However, with Deebo gone for a few weeks and Rachaad White potentially banged up this team's ceiling is low.

9. **The Dicker McDickersons** &nbsp;&nbsp; **+1**
    <br> This team took a good step forward in picking up a starting RB. Hopefully Tee Higgins comes back this week and adds some juice to this team, but until we see some upside from this squad it's hard to move them up too much.

10. **Two Curls One Kupp** &nbsp;&nbsp; **-9**
    <br> OOF! I don't think we've ever seen a team go from first to worst in the history of BWPR. You hate to see it, but with each of their first 3 round picks being put on IR, injuries to two other starters, and the rest of the squad underperforming expectations, the situation here is bleak.